apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore-vault-example
  namespace: eth-explorer    
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://localhost:8200"
    - name: skipVerify
      value: false
    - name: vaultToken
      value: mGT26cDdomWN7
    - name: vaultKVPrefix
      value: "CryptoAndFiatBilling/ethereumexplorer/eth_exp/prod"
    - name: enginePath
      value: "secret"